<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation"/>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nexos.Application.Interfaces\Nexos.Application.Interfaces.csproj"/>
    <ProjectReference Include="..\Nexos.Application.Dto\Nexos.Application.Dto.csproj"/>
    <ProjectReference Include="..\Nexos.Application.Validator\Nexos.Application.Validator.csproj" />
    <ProjectReference Include="..\Nexos.Domain.Entity\Nexos.Domain.Entity.csproj"/>
    <ProjectReference Include="..\Nexos.Transversal.Common\Nexos.Transversal.Common.csproj"/>
  </ItemGroup>

</Project>
